### ISSUE TITLE
Bind `ChatPage` for attachments in message

### ISSUE THREAD

**Issue by JayKim94** [JonasMuehlmann/BIB_VPR#149]
### UWP.Services
- [x] `ChatHubService` should provide method to upload `SelectedFiles` in `ChatPage`
- [ ] `ChatHubService` should provide method to download files from `AttachmentsBlobName` in `Message` model

### UWP.ViewModels
- [x] `ChatViewModel` should provide command for the view to invoke upload in `ChatHubService` with `SelectedFiles` in the view model
- [ ] `ChatViewModel` should provide command for the view to invoke download in `ChatHubService` with `AttachmentBlobNames` of a message

### UWP.Views
- [ ] On `ChatPage` users should be able to see attachment files in a message and invoke the command in `ChatViewModel` on click

**Comment by JonasMuehlmann** [comment]
Adding some resources to reference:
https://stackoverflow.com/questions/57708520/how-to-solve-the-problem-of-permission-denied-while-reading-a-file-from-uwp-appl
https://stackoverflow.com/questions/63649511/unauthorizedaccessexception-when-reading-files-from-downloads-folder-in-uwp
https://docs.microsoft.com/en-us/windows/uwp/files/

**Comment by robbelDev** [comment]
Can some body explain me were the problem is (were in the code)? There is also gone some code while mergin and we need some design to display the attachments when opened and in the message? @JayKim94

**Comment by JonasMuehlmann** [comment]
@robbelDev The responsible file is the [FileSharingService.cs](https://github.com/JonasMuehlmann/BIB_VPR/blob/unstable/Messenger/Messenger.Core/Services/FileSharingService.cs).
The problem, as far as I understand, is that conventional ways of doing file operations(with `System.IO`) does not work in UWP apps because they are sandboxed. Instead, one has to use the `Windows.Storage` namespace. Another problem is that UWP apps, by default, only have access to a few specific locations in the file system, and we need to set permissions to access the remaining locations.

**Comment by robbelDev** [comment]
@JonasMuehlmann can you look up whether I uploaded some files? :)

**Comment by JonasMuehlmann** [comment]
@robbelDev Did you upload the folder 2021?
